import { JobPosting } from '@/lib/jobs';

export const allJobs: JobPosting[] = [
  {
    id: '1',
    company: 'MrBeast',
    title: 'Senior Video Editor for MrBeast',
    logo: {
      'data-ai-hint': 'logo',
      src: 'https://yt3.ggpht.com/-egl0BJumF1A/AAAAAAAAAAI/AAAAAAAAAAA/zk1ch1-WaY8/s900-c-k-no-mo-rj-c0xffffff/photo.jpg',
      alt: 'MrBeast',
      children: 'MB',
    },
    platform: 'YouTube',
    job_description: "We're looking for a Senior Video Editor to join our post-production team. You will be responsible for editing our flagship videos, ensuring they meet the high standards of quality and engagement that our audience expects.",
    aboutJobDetails: 'As a Senior Video Editor, you will work closely with our creative directors and producers to bring our most ambitious ideas to life. This role requires a deep understanding of YouTube culture, storytelling, and viral content trends. You will have the opportunity to work on videos that reach millions of viewers and shape the future of online entertainment.',
    idealCandidate: [
      'Proven experience as a video editor in a fast-paced environment.',
      'Expertise in Adobe Premiere Pro, After Effects, and Photoshop.',
      'Strong storytelling skills and a deep understanding of pacing and rhythm.',
      'Ability to work under tight deadlines and manage multiple projects simultaneously.',
      'A passion for YouTube and a desire to create content that pushes creative boundaries.'
    ],
    jobRequirements: [
      'Minimum 5 years of professional video editing experience.',
      'A portfolio showcasing your best work, particularly on YouTube.',
      'Excellent communication and collaboration skills.',
      'Ability to receive and implement feedback effectively.'
    ],
    bonusSkills: [
        'Experience with color grading and sound design.',
        'Knowledge of motion graphics and VFX.',
        'Familiarity with the MrBeast brand and content style.'
    ],
    details: [
        'This is a full-time, remote position.',
        'Competitive salary and benefits package.',
        'Opportunity for growth and advancement within the company.'
    ],
    skills: {
        'Video Editing': ['Adobe Premiere Pro', 'Final Cut Pro', 'DaVinci Resolve', 'Adobe After Effects'],
        'Design': ['Adobe Photoshop', 'Adobe Illustrator'],
        'Audio': ['Adobe Audition', 'Audacity']
    },
    sampleVideos: [
        { title: '$1 vs $1,000,000 Hotel Room!', thumbnailUrl: 'https://i.ytimg.com/vi/iogcY_4xGjo/maxresdefault.jpg'},
        { title: 'I Spent 50 Hours In Solitary Confinement', thumbnailUrl: 'https://i.ytimg.com/vi/g4-fAJBCQ34/maxresdefault.jpg'},
        { title: 'Last To Leave Circle Wins $500,000', thumbnailUrl: 'https://i.ytimg.com/vi/ZxIDiJ6h3gA/maxresdefault.jpg'}
    ],
    salary: '$80k - $120k',
    location: 'New York, USA',
    remote: 'Yes',
    job_time: 'Full-time',
    posted_at: '2 hours ago',
    applicants: 132,
    startDate: 'ASAP',
    contentFormat: 'Long-form video',
    language: 'English',
    followers: '250M',
    referralBonus: '$2,000'
  },
  {
    id: '2',
    company: 'PewDiePie',
    title: 'Thumbnail Designer',
    logo: {
      'data-ai-hint': 'logo',
      src: 'https://i.pinimg.com/originals/7e/f7/77/7ef7776d02efd1c241bf547b0a8cb719.png',
      alt: 'PewDiePie',
      children: 'PD',
    },
    platform: 'YouTube',
    job_description: 'Seeking a talented Thumbnail Designer to create eye-catching and clickable thumbnails for our YouTube channel. You will play a crucial role in our content strategy by designing visuals that attract viewers and increase click-through rates.',
    salary: '$50/hour',
    location: 'Remote',
    remote: 'Yes',
    job_time: 'Contract',
    posted_at: '1 day ago',
    applicants: 87,
    startDate: 'Next Month',
    contentFormat: 'Thumbnails',
    language: 'English',
    followers: '111M',
  },
  {
    id: '3',
    company: 'Pokimane',
    title: 'Community Manager for Twitch & Discord',
    logo: {
      'data-ai-hint': 'logo',
      src: 'https://dotesports.com/wp-content/uploads/2022/08/22211037/Feature-Image-58.jpg?w=1200',
      alt: 'Pokimane',
      children: 'P',
    },
    platform: 'Twitch',
    job_description: 'We are looking for an experienced Community Manager to foster a positive and engaging community across Twitch and Discord. You will be responsible for moderation, organizing events, and interacting with our amazing fanbase.',
    salary: '$60k - $75k',
    location: 'Los Angeles, CA',
    remote: 'No',
    job_time: 'Full-time',
    posted_at: '3 days ago',
    applicants: 201,
    startDate: 'ASAP',
    contentFormat: 'Community',
    language: 'English, French',
    followers: '9.3M',
  },
  {
    id: '4',
    company: 'Dude Perfect',
    title: 'Stunt Coordinator & Safety Officer',
    logo: {
      'data-ai-hint': 'logo',
      src: 'https://tse2.mm.bing.net/th/id/OIP.f42QszETJqaT7Jq9rdsubQHaHa?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
      alt: 'Dude Perfect',
      children: 'DP',
    },
    platform: 'YouTube',
    job_description: 'Join the Dude Perfect team as a Stunt Coordinator and Safety Officer. You will be responsible for planning, choreographing, and ensuring the safety of all our stunts and trick shots. This is a high-energy role for someone with a passion for action and a commitment to safety.',
    salary: '$90k - $110k',
    location: 'Frisco, TX',
    remote: 'No',
    job_time: 'Full-time',
    posted_at: '5 days ago',
    applicants: 45,
    startDate: 'In 2 Weeks',
    contentFormat: 'Live Action',
    language: 'English',
    followers: '60M',
  },
  {
    id: '5',
    company: 'Emma Chamberlain',
    title: 'Podcast Producer & Audio Engineer',
    logo: {
      'data-ai-hint': 'logo',
      src: 'https://media1.popsugar-assets.com/files/thumbor/ivPwCzKnGH1rfzP-ZwxU7mBZjKo/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2021/05/07/790/n/1922153/tmp_aN0w1Q_1c08c95c2518faaa_GettyImages-1152470007.jpg',
      alt: 'Emma Chamberlain',
      children: 'EC',
    },
    platform: 'YouTube',
    job_description: 'We are looking for a Podcast Producer and Audio Engineer for the "Anything Goes" podcast. You will be responsible for recording, editing, and mixing audio, as well as helping with content planning and guest coordination.',
    salary: '$70k - $85k',
    location: 'Los Angeles, CA',
    remote: 'Hybrid',
    job_time: 'Full-time',
    posted_at: '1 week ago',
    applicants: 112,
    startDate: 'ASAP',
    contentFormat: 'Podcast',
    language: 'English',
    followers: '12M',
  },
  {
    id: '6',
    company: 'MKBHD',
    title: 'Social Media Manager (X & Instagram)',
    logo: {
      'data-ai-hint': 'logo',
      src: 'https://yt3.ggpht.com/-lNGwllze1Xk/AAAAAAAAAAI/AAAAAAAAAAA/N6QnsHGN7Fk/s900-c-k-no/photo.jpg',
      alt: 'MKBHD',
      children: 'M',
    },
    platform: 'X',
    job_description: 'Seeking a Social Media Manager to run the MKBHD Twitter (X) and Instagram accounts. You will be responsible for creating engaging content, interacting with the tech community, and promoting our latest videos.',
    salary: '$65k - $80k',
    location: 'Kearny, NJ',
    remote: 'No',
    job_time: 'Full-time',
    posted_at: '1 week ago',
    applicants: 150,
    startDate: 'Next Month',
    contentFormat: 'Social Media',
    language: 'English',
    followers: '18.5M',
  },
  {
    id: '7',
    company: 'OfflineTV',
    title: 'Production Assistant',
    logo: {
      'data-ai-hint': 'logo',
      src: 'https://i.redd.it/s5u88y7p17c61.png',
      alt: 'OfflineTV',
      children: 'OTV',
    },
    platform: 'YouTube',
    job_description: 'OfflineTV is hiring a Production Assistant to support our video production team. You will assist with setting up shoots, managing equipment, and ensuring everything runs smoothly on set. This is a great opportunity for someone looking to get into the world of online video production.',
    salary: '$25/hour',
    location: 'Los Angeles, CA',
    remote: 'No',
    job_time: 'Part-time',
    posted_at: '10 days ago',
    applicants: 300,
    startDate: 'ASAP',
    contentFormat: 'Live Action',
    language: 'English',
    followers: '3.2M',
  },
  {
    id: '8',
    company: 'St-Laurent',
    title: 'Motion Designer',
    logo: {
      'data-ai-hint': 'logo',
      src: 'https://www.tuttivip.it/wp-content/uploads/2021/04/st-laurent-logo.jpg',
      alt: 'St-Laurent',
      children: 'SL',
    },
    platform: 'Instagram',
    job_description: 'We are looking for a talented Motion Designer to create stunning visual content for our Instagram and other social media platforms. You will work with our creative team to produce animations, and other motion graphics that align with the St-Laurent brand.',
    salary: '$85k - $100k',
    location: 'Paris, France',
    remote: 'Hybrid',
    job_time: 'Full-time',
    posted_at: '2 weeks ago',
    applicants: 95,
    startDate: 'In 1 Month',
    contentFormat: 'Motion Graphics',
    language: 'French, English',
    followers: '11M',
  },
  {
    id: '9',
    company: 'Twitch',
    title: 'Partner Manager',
    logo: {
        'data-ai-hint': 'logo',
        src: 'https://media.licdn.com/dms/image/D560BAQGssG3mM1tDqA/company-logo_200_200/0/1715699991243/twitch_logo?e=1730332800&v=beta&t=3Zq_R1n7AWB-tLS5A-2v7K2T6jW-yP1-g7c0S5z3Y-U',
        alt: 'Twitch',
        children: 'T',
    },
    platform: 'Twitch',
    job_description: 'Twitch is looking for a Partner Manager to build and maintain relationships with our top creators. You will be their main point of contact, helping them grow their channels, and ensuring they have the support they need to succeed.',
    salary: '$100k - $130k',
    location: 'San Francisco, CA',
    remote: 'Yes',
    job_time: 'Full-time',
    posted_at: '2 weeks ago',
    applicants: 120,
    startDate: 'ASAP',
    contentFormat: 'Partnerships',
    language: 'English',
    followers: '10.5M',
  }
];
