
export const portfolioItems = [
  {
    id: '1',
    title: 'I Bought 1,000 Banned Amazon Products!',
    thumbnailUrl: 'https://i.ytimg.com/vi/r_DtA6A53sM/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=r_DtA6A53sM',
    views: '93.75M views',
    likes: '638.57K Likes',
    tag: 'Thumbnail Designer',
    verified: false,
    creatorAvatarUrl: 'https://yt3.ggpht.com/-lNGwllze1Xk/AAAAAAAAAAI/AAAAAAAAAAA/N6QnsHGN7Fk/s900-c-k-no/photo.jpg',
  },
  {
    id: '2',
    title: 'OFFLINETV RATATOUILLE COOKING CHALLENGE',
    thumbnailUrl: 'https://i.ytimg.com/vi/DnT_bupQz1c/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=DnT_bupQz1c',
    views: '2.95M views',
    likes: '103.58K Likes',
    tag: 'Thumbnail Designer',
    verified: false,
    creatorAvatarUrl: 'https://i.redd.it/s5u88y7p17c61.png',
  },
  {
    id: '3',
    title: 'I Fooled Villagers in Most EPIC WAYS in Minecraft!',
    thumbnailUrl: 'https://i.ytimg.com/vi/S-9oBEi7_cE/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=S-9oBEi7_cE',
    views: '5.2M views',
    likes: '41.86K Likes',
    tag: 'Thumbnail Designer',
    verified: false,
    creatorAvatarUrl: 'https://yt3.googleusercontent.com/ytc/AIdro_k-T35YGE2i_53Ue-U4r1u-zuI1pYk3LwG2QJ4a2Q=s900-c-k-c0x00ffffff-no-rj',
  },
  {
    id: '4',
    title: '8 GREATEST NBA TRADES THAT ALMOST HAPPENED',
    thumbnailUrl: 'https://i.ytimg.com/vi/a-s7y1g2p6s/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=a-s7y1g2p6s',
    views: '1.2M views',
    likes: '7.3K Likes',
    tag: 'Thumbnail Designer',
    verified: true,
  },
  {
    id: '5',
    title: 'I Got Signed To A Professional Football Team!',
    thumbnailUrl: 'https://i.ytimg.com/vi/crx0t_pI-b8/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=crx0t_pI-b8',
    views: '3.32M views',
    likes: '49.35K Likes',
    tag: 'Thumbnail Designer',
    verified: false,
  },
  {
    id: '6',
    title: 'Road To JUNIOR OLYMPICS !!!',
    thumbnailUrl: 'https://i.ytimg.com/vi/G2Xy51y2yW8/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=G2Xy51y2yW8',
    views: '462.66K views',
    likes: '4.95K Likes',
    tag: 'Thumbnail Designer',
    verified: false,
  },
  {
    id: '7',
    title: 'Eating Only Cartoon Food For 24 Hours!',
    thumbnailUrl: 'https://i.ytimg.com/vi/3fG35Yqff6o/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=3fG35Yqff6o',
    views: '7.94M views',
    likes: '126.4K Likes',
    tag: 'Thumbnail Designer',
    verified: false,
  },
  {
    id: '8',
    title: "Eating the Worlds Spiciest VS Sourest Food - Challenge",
    thumbnailUrl: 'https://i.ytimg.com/vi/zFLm_d5D06A/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=zFLm_d5D06A',
    views: '20.48M views',
    likes: '221.25K Likes',
    tag: 'Thumbnail Designer',
    verified: false,
  },
  {
    id: '9',
    title: 'I Opened a $1 Shoe Store',
    thumbnailUrl: 'https://i.ytimg.com/vi/yX39J_YyKbs/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=yX39J_YyKbs',
    views: '5.94M views',
    likes: '108.37K Likes',
    tag: 'Thumbnail Designer',
    verified: false,
  },
];

export const clients = [
    { name: 'LostNUnbound', avatarUrl: 'https://picsum.photos/seed/client1/40/40', subscribers: '1.78M subscribers' },
    { name: 'Ben Azelart', avatarUrl: 'https://picsum.photos/seed/client2/40/40', subscribers: '47M subscribers' },
    { name: 'FaZe Rug', avatarUrl: 'https://picsum.photos/seed/client3/40/40', subscribers: '28.4M subscribers' },
    { name: 'Netflix India', avatarUrl: 'https://picsum.photos/seed/client4/40/40', subscribers: '27.8M subscribers' },
    { name: 'Raj Shamani', avatarUrl: 'https://picsum.photos/seed/client5/40/40', subscribers: '12.9M subscribers' },
    { name: 'Tech Burner', avatarUrl: 'https://picsum.photos/seed/client6/40/40', subscribers: '12.5M subscribers' },
    { name: 'JioHotstar', avatarUrl: 'https://picsum.photos/seed/client7/40/40', subscribers: '11.4M subscribers' },
    { name: 'Inoxtag', avatarUrl: 'https://picsum.photos/seed/client8/40/40', subscribers: '9.28M subscribers' },
    { name: 'Tyler Oliveira', avatarUrl: 'https://picsum.photos/seed/client9/40/40', subscribers: '8.23M subscribers' },
    { name: 'JONATHAN GAMING', avatarUrl: 'https://picsum.photos/seed/client10/40/40', subscribers: '7.32M subscribers' },
    { name: 'fern', avatarUrl: 'https://picsum.photos/seed/client11/40/40', subscribers: '3.98M subscribers' },
    { name: 'Carry Depie', avatarUrl: 'https://picsum.photos/seed/client12/40/40', subscribers: '3.34M subscribers' },
    { name: 'OfflineTV', avatarUrl: 'https://picsum.photos/seed/client13/40/40', subscribers: '3.28M subscribers' },
];
